// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TechGearStore.Data;

#nullable disable

namespace TechGearStor.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TechGearStore.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsFeatured")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "Peripherals",
                            Description = "RGB Backlit Tactile Switches",
                            ImageUrl = "/images/keyboard.jpg",
                            IsFeatured = true,
                            Name = "Mechanical Gaming Keyboard",
                            Price = 89.99m
                        },
                        new
                        {
                            Id = 2,
                            Category = "Peripherals",
                            Description = "High Precision Optical Sensor",
                            ImageUrl = "/images/mouse.jpg",
                            IsFeatured = true,
                            Name = "Ergonomic Wireless Mouse",
                            Price = 49.99m
                        },
                        new
                        {
                            Id = 3,
                            Category = "Monitors",
                            Description = "144Hz 4K Curved Display",
                            ImageUrl = "/images/monitor.jpg",
                            IsFeatured = false,
                            Name = "UltraWide 34-inch Monitor",
                            Price = 499.99m
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
